### ISSUE TITLE
Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)

### ISSUE THREAD

**Issue by ArghyaChatterjee** [mrfmap/mrfmap_ros#1]
Hello, I was trying to reproduce your work. I was able to download and run mrfmap library file and test the program ./testMRFMapViewer file. Everything seemed ok at that point. Then I followed mrfmap_ros tutorial, I did the following:
```
sudo apt install python-virtualenv
virtualenv ~/virtualenv
source ~/virtualenv/bin/activate
pip install -U vtk PyYAML mayavi matplotlib numpy scipy PyGeometry==1.5.6 opencv-python click
cd ~ && mkdir -P sandbox/mrfmap_sandbox/src && cd sandbox/mrfmap_sandbox && catkin init
catkin config -DCMAKE_BUILD_TYPE=Release 
catkin config --install
cd src && git clone https://github.com/mrfmap/mrfmap_ros.git
catkin build mrfmap_ros
```
So I got the following result:
```
arghya@arghya-Erazer-X7849-MD60379:~/sandbox/mrfmap_sandbox/src$ catkin build mrfmap_ros
--------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/arghya/ws_moveit/devel:/opt/ros/melodic
Workspace:                   /home/arghya/sandbox/mrfmap_sandbox
--------------------------------------------------------------------------
Build Space:        [exists] /home/arghya/sandbox/mrfmap_sandbox/build
Devel Space:        [exists] /home/arghya/sandbox/mrfmap_sandbox/devel
Install Space:      [exists] /home/arghya/sandbox/mrfmap_sandbox/install
Log Space:          [exists] /home/arghya/sandbox/mrfmap_sandbox/logs
Source Space:       [exists] /home/arghya/sandbox/mrfmap_sandbox/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        merged
--------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------
[build] Found '1' packages in 0.0 seconds.                                                                         
Starting  >>> mrfmap_ros                                                                                           
___________________________________________________________________________________________________________________
Errors     << mrfmap_ros:cmake /home/arghya/sandbox/mrfmap_sandbox/logs/mrfmap_ros/build.cmake.004.log             
CMake Error at /opt/cmake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "3.3.7")
Call Stack (most recent call first):
  /opt/cmake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindEigen3.cmake:76 (find_package_handle_standard_args)
  CMakeLists.txt:26 (find_package)


cd /home/arghya/sandbox/mrfmap_sandbox/build/mrfmap_ros; catkin build --get-env mrfmap_ros | catkin env -si  /usr/local/bin/cmake /home/arghya/sandbox/mrfmap_sandbox/src/mrfmap_ros --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/arghya/sandbox/mrfmap_sandbox/devel/.private/mrfmap_ros -DCMAKE_INSTALL_PREFIX=/home/arghya/sandbox/mrfmap_sandbox/install -DCMAKE_BUILD_TYPE=Release; cd -
...................................................................................................................
Failed     << mrfmap_ros:cmake          [ Exited with code 1 ]                                                     
Failed    <<< mrfmap_ros                [ 0.6 seconds ]                                                            
[build] Summary: 0 of 1 packages succeeded.                                                                        
[build]   Ignored:   None.                                                                                         
[build]   Warnings:  None.                                                                                         
[build]   Abandoned: None.                                                                                         
[build]   Failed:    1 packages failed. 
``` 
Here is my log file:
[build.cmake.004.log](https://github.com/mrfmap/mrfmap_ros/files/5075324/build.cmake.004.log)
Now the problem seems to me is that it's the eigen version mismatch. Here are the things that I changed:

1. After fresh clone of mrfmap_ros repo, I replaced a line of Cmakelist.txt file with the default MRFMAP PATH '/home/icoderaven/packages/mrfmap/install/share/cmake/' with '/home/arghya/mrfmap/install/share/cmake/' (my default mrfmap library installed path). 

2. Initially before building mrfmap library, I had Cmake version 3.10. I downloaded the Cmake 3.18 manually and installed it on the system. The command 'cmake --version' showed 3.18.1. 

3. Initially before building mrfmap library, I had Eigen version 3.3.4. So, in order to upgrade, I downloaded version 3.3.7. Manually copied the 'Eigen' subdirectory of  'eigen-eigen-323c052e1731' directory (which was generated after extracting the eigen-eigen-323c052e1731.tar.bz2 file) from /home/arghya/Downloads directory to /usr/local/include directory. So at this point, my /usr/include directory has a 'Eigen' subdirectory where the version is 3.3.4 where as my /usr/local/include has a 'Eigen' subdirectory where the version is 3.3.7.
         
4. So, after this stage, I tried to build the mrfmap library which worked and seemed ok (as I was able to run the test file in open3D). Then I tried to build mrfmap_ros package with 'catkin build mrfmap_ros'. The same error occured shown above. 

5. So, I thought that this may be due to version mismatch of eigen. So, I deleted the subdirectory named 'Eigen' (version 3.3.4)  in usr/include/ directory and replaced it with subdirectory named 'Eigen'  (version 3.3.7) which was in usr/local/include directory. Then I repeated the workflow of no. 4 but got the same error.

6. Then I thought may be I should try to build the  'eigen-eigen-323c052e1731' directory (which was generated after extracting the eigen-eigen-323c052e1731.tar.bz2 file). So inside the 'eigen-eigen-323c052e1731' directory, I created a subdirectory build with 'mkdir build' && cd build' and 'cmake ..' and then 'sudo make install' command. Though it appeared the same (copied the 'Eigen' subdirectory (basically header files) to /usr/local/include directory which I previously did manually), I repeated the workflow of no. 4 but got the same error.

Now I have 2 'Eigen' subdirectories with the same version (3.3.7). One inside /usr/include directory and one inside /usr/local/include directory. Still the problem persists. 

I am using ubuntu 18.04 machine with nvidia graphics card 1070, graphics driver version 440 and CUDA version 10.2.   

It appeared to me that there are some 'cache' directory from where it is reading the version (which may be 3.3.4) and that's why after changing 'Eigen' header files in the actual directories, cmake is not taking into account whether the actual version has changed or not. It's reading the cached version and showing the error. Can anybody help ??

**Comment by icoderaven** [comment]
Hi @ArghyaChatterjee! 
If you look at https://github.com/mrfmap/mrfmap_ros/blob/94416bfae6f4dc3772a1121fd2d10bef3170a685/CMakeLists.txt#L23

All you need to do is point an environment variable to your Eigen 3.3.7 directory
```
export EIGEN3_INCLUDE_DIR=/path/to/eigen
```
and then do a ```catkin clean``` before building.

As a side note, avoid changing contents of your /usr/include since other packages in your system might depend on it.

Let me know if this helps!

**Comment by ArghyaChatterjee** [comment]
Hi @icoderaven , thanks for your reply. It helped a lot. However, the package still didn't build correctly. So, initially inside the virtual environment, I tried to install the libraries as you mentioned with the command ```pip install -U vtk PyYAML mayavi matplotlib numpy scipy PyGeometry==1.5.6 opencv-python click```. The error shows up something like this:
```
(virtualenv) arghya@arghya-Erazer-X7849-MD60379:~$ pip install -U vtk PyYAML mayavi matplotlib numpy scipy PyGeometry==1.5.6 opencv-python click
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: vtk in ./virtualenv/lib/python2.7/site-packages (8.1.2)
Requirement already up-to-date: PyYAML in ./virtualenv/lib/python2.7/site-packages (5.3.1)
Requirement already up-to-date: mayavi in ./virtualenv/lib/python2.7/site-packages (4.7.1)
Requirement already up-to-date: matplotlib in ./virtualenv/lib/python2.7/site-packages (2.2.5)
Requirement already up-to-date: numpy in ./virtualenv/lib/python2.7/site-packages (1.16.6)
Requirement already up-to-date: scipy in ./virtualenv/lib/python2.7/site-packages (1.2.3)
Requirement already up-to-date: PyGeometry==1.5.6 in ./virtualenv/lib/python2.7/site-packages (1.5.6)
Collecting opencv-python
  Using cached opencv-python-4.3.0.38.tar.gz (88.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/arghya/virtualenv/bin/python2 /home/arghya/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpALU67E
       cwd: /tmp/pip-install-T2hiB6/opencv-python
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/home/arghya/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/arghya/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/arghya/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/home/arghya/virtualenv/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/home/arghya/virtualenv/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/home/arghya/virtualenv/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/home/arghya/virtualenv/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      main()
    File "setup.py", line 99, in main
      % {"ext": re.escape(sysconfig.get_config_var("EXT_SUFFIX"))}
    File "/home/arghya/virtualenv/lib/python2.7/re.py", line 210, in escape
      s = list(pattern)
  TypeError: 'NoneType' object is not iterable
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/arghya/virtualenv/bin/python2 /home/arghya/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpALU67E Check the logs for full command output.
```
The error is about opencv. Actually I ignored it previously thinking that I have opencv 3.4.8 installed for both python 2.7 and python 3.6.9 version so may be it is not a major problem. 

Now after your suggestion, I changed the environment variable to permanently source eigen3 directory to my .bashrc file hence to the terminal. Now, another error shows up like this:
```
 (virtualenv) arghya@arghya-Erazer-X7849-MD60379:~/sandbox/mrfmap_sandbox/src$ catkin build mrfmap_ros
--------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/arghya/ws_moveit/devel:/opt/ros/melodic
Workspace:                   /home/arghya/sandbox/mrfmap_sandbox
--------------------------------------------------------------------------
Build Space:        [exists] /home/arghya/sandbox/mrfmap_sandbox/build
Devel Space:        [exists] /home/arghya/sandbox/mrfmap_sandbox/devel
Install Space:      [exists] /home/arghya/sandbox/mrfmap_sandbox/install
Log Space:          [exists] /home/arghya/sandbox/mrfmap_sandbox/logs
Source Space:       [exists] /home/arghya/sandbox/mrfmap_sandbox/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        merged
--------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------
[build] Found '1' packages in 0.0 seconds.                                                                                                                           
Starting  >>> mrfmap_ros                                                                                                                                             
_____________________________________________________________________________________________________________________________________________________________________
Errors     << mrfmap_ros:make /home/arghya/sandbox/mrfmap_sandbox/logs/mrfmap_ros/build.make.001.log                                                                 
/usr/bin/ld: cannot find -lThreads::Threads
collect2: error: ld returned 1 exit status
make[2]: *** [/home/arghya/sandbox/mrfmap_sandbox/devel/.private/mrfmap_ros/lib/mrfmap_ros/GVDBBatchMapCreator] Error 1
make[1]: *** [CMakeFiles/GVDBBatchMapCreator.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lThreads::Threads
collect2: error: ld returned 1 exit status
make[2]: *** [/home/arghya/sandbox/mrfmap_sandbox/devel/.private/mrfmap_ros/lib/mrfmap_ros/ros_mrfmap_node] Error 1
make[1]: *** [CMakeFiles/ros_mrfmap_node.dir/all] Error 2
/usr/bin/ld: cannot find -lThreads::Threads
collect2: error: ld returned 1 exit status
make[2]: *** [/home/arghya/sandbox/mrfmap_sandbox/devel/.private/mrfmap_ros/lib/MRFMapRosPyModules.so] Error 1
make[1]: *** [CMakeFiles/MRFMapRosPyModules.dir/all] Error 2
make: *** [all] Error 2
cd /home/arghya/sandbox/mrfmap_sandbox/build/mrfmap_ros; catkin build --get-env mrfmap_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.....................................................................................................................................................................
Failed     << mrfmap_ros:make           [ Exited with code 2 ]                                                                                                       
Failed    <<< mrfmap_ros                [ 0.3 seconds ]                                                                                                              
[build] Summary: 0 of 1 packages succeeded.                                                                                                                          
[build]   Ignored:   None.                                                                                                                                           
[build]   Warnings:  None.                                                                                                                                           
[build]   Abandoned: None.                                                                                                                                           
[build]   Failed:    1 packages failed.                                                                                                                              
[build] Runtime: 0.4 seconds total. 
```
Your help is much appreciated. Eagerly waiting for your response. TIA.

By the way I was able to produce half of your work [here](https://www.youtube.com/watch?v=L650IYt4oZc).

**Comment by icoderaven** [comment]
For the first error, sometimes pip doesn't get dependencies correctly resolved, so it requires finding dependencies manually by searching for errors and installing them. Let me know if you are still struggling, and I'll try to set up a fresh instance to figure it out.

For the latter case, it seems that the transitive pthreads dependency is not working out. Can you add this line 
```
find_package(Threads REQUIRED)
```
to the CMakeLists.txt and check on a clean rebuild?

**Comment by ArghyaChatterjee** [comment]
So, according to your suggestion, I added the line ```find_package(Threads REQUIRED)``` to my CMakeLists.txt file, performed a ```catkin clean``` inside 'src' folder and initiated ```catkin build mrfmap_ros```. The problem seem to be resolved from then on. However, another problem occured regarding 'catkin_pkg' package.  
```
(virtualenv) arghya@arghya-Erazer-X7849-MD60379:~/sandbox/mrfmap_sandbox/src$ catkin build mrfmap_ros
--------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/arghya/ws_moveit/devel:/opt/ros/melodic
Workspace:                   /home/arghya/sandbox/mrfmap_sandbox
--------------------------------------------------------------------------
Build Space:        [exists] /home/arghya/sandbox/mrfmap_sandbox/build
Devel Space:        [exists] /home/arghya/sandbox/mrfmap_sandbox/devel
Install Space:     [missing] /home/arghya/sandbox/mrfmap_sandbox/install
Log Space:         [missing] /home/arghya/sandbox/mrfmap_sandbox/logs
Source Space:       [exists] /home/arghya/sandbox/mrfmap_sandbox/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        merged
--------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
--------------------------------------------------------------------------
[build] Found '1' packages in 0.0 seconds.                                                
Starting  >>> catkin_tools_prebuild                                                       
__________________________________________________________________________________________
Errors     << catkin_tools_prebuild:cmake /home/arghya/sandbox/mrfmap_sandbox/logs/catkin_tools_prebuild/build.cmake.000.log
ImportError: "from catkin_pkg.package import parse_package" failed: No module named catkin_pkg.package
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH.
CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/home/arghya/virtualenv/bin/python2
  "/opt/ros/melodic/share/catkin/cmake/parse_package_xml.py"
  "/opt/ros/melodic/share/catkin/cmake/../package.xml"
  "/home/arghya/sandbox/mrfmap_sandbox/build/catkin_tools_prebuild/catkin/catkin_generated/version/package.cmake")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkin_package_xml.cmake:74 (safe_execute_process)
  /opt/ros/melodic/share/catkin/cmake/all.cmake:168 (_catkin_package_xml)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)


cd /home/arghya/sandbox/mrfmap_sandbox/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/local/bin/cmake /home/arghya/sandbox/mrfmap_sandbox/build/catkin_tools_prebuild --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/arghya/sandbox/mrfmap_sandbox/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/home/arghya/sandbox/mrfmap_sandbox/install -DCMAKE_BUILD_TYPE=Release; cd -
..........................................................................................
Failed     << catkin_tools_prebuild:cmake          [ Exited with code 1 ]                 
Failed    <<< catkin_tools_prebuild                [ 0.9 seconds ]                        
Abandoned <<< mrfmap_ros                           [ Unrelated job failed ]               
[build] Summary: 0 of 2 packages succeeded.                                               
[build]   Ignored:   None.                                                                
[build]   Warnings:  None.                                                                
[build]   Abandoned: 1 packages were abandoned.                                           
[build]   Failed:    1 packages failed.                                                   
[build] Runtime: 1.0 seconds total.  
```
So, after I added python path (version 2.7.17) into the .bashrc file (export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages), I opened a new terminal, moved to the 'src' directory, performed a ```catkin clean``` and then executed ```catkin build mrfmap_ros```. The program was able to find out catkin_pkg. I somehow managed to build the package with a warning regarding opencv version:
```
(virtualenv) arghya@arghya-Erazer-X7849-MD60379:~/sandbox/mrfmap_sandbox/src$ catkin build mrfmap_ros
--------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/arghya/ws_moveit/devel:/opt/ros/melodic
Workspace:                   /home/arghya/sandbox/mrfmap_sandbox
--------------------------------------------------------------------------
Build Space:        [exists] /home/arghya/sandbox/mrfmap_sandbox/build
Devel Space:        [exists] /home/arghya/sandbox/mrfmap_sandbox/devel
Install Space:     [missing] /home/arghya/sandbox/mrfmap_sandbox/install
Log Space:         [missing] /home/arghya/sandbox/mrfmap_sandbox/logs
Source Space:       [exists] /home/arghya/sandbox/mrfmap_sandbox/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        merged
--------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
--------------------------------------------------------------------------
[build] Found '1' packages in 0.0 seconds.                                                                                
Starting  >>> catkin_tools_prebuild                                                                                       
Finished  <<< catkin_tools_prebuild                [ 1.2 seconds ]                                                        
Starting  >>> mrfmap_ros                                                                                                  
__________________________________________________________________________________________________________________________
Warnings   << mrfmap_ros:make /home/arghya/sandbox/mrfmap_sandbox/logs/mrfmap_ros/build.make.000.log                      
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.3.4
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.3.4
cd /home/arghya/sandbox/mrfmap_sandbox/build/mrfmap_ros; catkin build --get-env mrfmap_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..........................................................................................................................
Finished  <<< mrfmap_ros                           [ 32.7 seconds ]                                                       
[build] Summary: All 2 packages succeeded!                                                                                
[build]   Ignored:   None.                                                                                                
[build]   Warnings:  1 packages succeeded with warnings.                                                                  
[build]   Abandoned: None.                                                                                                
[build]   Failed:    None.                                                                                                
[build] Runtime: 33.9 seconds total.                                                                                      
[build] Note: Workspace packages have changed, please re-source setup files to use them.
```
A little observation:

1. When initiating the command ```mkdir -P sandbox/mrfmap_sandbox/src && cd sandbox/mrfmap_sandbox && catkin init```, (which is basically making a directory) using a capital 'P' as flag is throwing error. Small 'p' seems to resolve the issue.
2. Same is the case with ```mkdir -P ~/bagfiles/ICL && cd ~/bagfiles/ICL```. Small 'p' seems to resolve the issue.

**Comment by icoderaven** [comment]
Good catch with the -P flag! Also, it seems like you have multiple opencv version installed to system? Generally not a recommended situation even if the different libraries are ABI compatible.

**Comment by icoderaven** [comment]
Closing the issue since the main issue appears to be resolved.
